version: '3.5'

services:
  server:
    build:
      context: api/
    ports:
      - '8081:3000'
    restart: always
    networks:
      - mysql
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_IP: db
    depends_on:
      - db

  front:
    build:
      context: front/
    ports:
      - '8080:8080'
    restart: unless-stopped

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tripplanner
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    restart: always
    networks:
      - mysql
    ports:
      - 8890:80
    environment:
      PMA_HOST: db

networks:
  mysql:
    name: mysql
