# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build docker app
        run: docker-compose build && docker-compose up -d
      - name: Run tests in api
        run: cd api/ && npm i && npm test
      - name: Run tests in front
        run: cd front/ && npm i && npm run test
